services:
  frontend:
    build:
      context: .
      args:
        - BUN_IMAGE=${BUN_IMAGE}
      dockerfile: ./Dockerfile.dev.front
    container_name: frontApp
    working_dir: /workspace/client
    environment:
      PROXY_PORT: ${DEV_PROXY_PORT}
      PROXY_HOST: ${DEV_PROXY_CONTAINER_NAME}
      VITE_PORT: ${VITE_PORT}
      VITE_CLIENT_ID: ${ENTRA_CLIENT_ID}
      VITE_AUTHORITY: ${ENTRA_TENANT_ID}
      VITE_REDIRECT_URI: ${ENTRA_REDIRECT_URI}
      VITE_URI: ${URI}

    tty: true
    volumes:
      - ../..:/workspace:cached

    restart: always
    command: /bin/sh -c "while sleep 1000; do :; done"
